In [ ]:
import pandas as pd
from google.colab import files

# Upload your CSV file
uploaded = files.upload()

# Get the uploaded filename
file_name = next(iter(uploaded))

# Read the dataset
df = pd.read_csv(file_name)

# Basic information
print("========== DATASET INFORMATION ==========")
print("File name:", file_name)
print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))

print("\n========== COLUMN NAMES ==========")
for i, column in enumerate(df.columns, 1):
    print(f"{i}. {column}")

print("\n========== FIRST 5 ROWS ==========")
display(df.head())

print("\n========== DATA TYPES ==========")
print(df.dtypes)

print("\n========== MISSING VALUES ==========")
missing = df.isnull().sum()
print(missing[missing > 0])

print("\n========== UNIQUE VALUES ==========")
for column in df.columns:
    print(f"{column}: {df[column].nunique()} unique values")

Saving 2020_al_data_kaggle_upload_new_old_syllabi.csv to 2020_al_data_kaggle_upload_new_old_syllabi (1).csv
========== DATASET INFORMATION ==========
File name: 2020_al_data_kaggle_upload_new_old_syllabi (1).csv
Number of rows: 337553
Number of columns: 19

========== COLUMN NAMES ==========
1. index
2. stream
3. Zscore
4. district_rank
5. island_rank
6. al_year
7. sub1
8. sub1_r
9. sub2
10. sub2_r
11. sub3
12. sub3_r
13. cgt_r
14. ge_r
15. syllabus
16. birth_day
17. birth_month
18. birth_year
19. gender

========== FIRST 5 ROWS ==========

,index,stream,Zscore,district_rank,island_rank,al_year,sub1,sub1_r,sub2,sub2_r,sub3,sub3_r,cgt_r,ge_r,syllabus,birth_day,birth_month,birth_year,gender
0,0,ARTS,-.3550,4336 (NEW),64994 (NEW),2020,POLITICAL SCIENCE,S,DANCING(BHARATHA),C,TAMIL,S,056,S,new,31,May,2001,female
1,1,ARTS,-.2648,4154 (NEW),62338 (NEW),2020,POLITICAL SCIENCE,S,CARNATIC MUSIC,C,TAMIL,C,032,C,new,13,January,2002,female
2,2,COMMERCE,-.4760,6910 (NEW),37307 (NEW),2020,ECONOMICS,S,BUSINESS STUDIES,S,ACCOUNTING,S,050,S,new,16,August,2001,female
3,3,COMMERCE,-.1012,5678 (NEW),30449 (NEW),2020,ECONOMICS,C,BUSINESS STUDIES,C,ACCOUNTING,S,034,S,new,16,August,2001,female
4,4,COMMERCE,.6014,3269 (NEW),17010 (NEW),2020,ECONOMICS,C,BUSINESS STUDIES,C,ACCOUNTING,B,036,S,new,7,August,2000,female

========== DATA TYPES ==========
index             int64
stream           object
Zscore           object
district_rank    object
island_rank      object
al_year           int64
sub1             object
sub1_r           object
sub2             object
sub2_r           object
sub3             object
sub3_r           object
cgt_r            object
ge_r             object
syllabus         object
birth_day        object
birth_month      object
birth_year       object
gender           object
dtype: object

========== MISSING VALUES ==========
gender    1484
dtype: int64

========== UNIQUE VALUES ==========
index: 337553 unique values
stream: 8 unique values
Zscore: 33891 unique values
district_rank: 8060 unique values
island_rank: 47616 unique values
al_year: 1 unique values
sub1: 51 unique values
sub1_r: 7 unique values
sub2: 60 unique values
sub2_r: 7 unique values
sub3: 60 unique values
sub3_r: 8 unique values
cgt_r: 73 unique values
ge_r: 7 unique values
syllabus: 2 unique values
birth_day: 34 unique values
birth_month: 15 unique values
birth_year: 76 unique values
gender: 3 unique values

In [ ]:
# ==========================================
# CELL 2 - CLEAN THE DATA
# ==========================================

import pandas as pd
import numpy as np

# Make a copy
clean_df = df.copy()

# ------------------------------------------
# 1. Clean Z-score
# ------------------------------------------

clean_df["Zscore"] = (
    clean_df["Zscore"]
    .astype(str)
    .str.strip()
    .replace(["nan", "None", ""], np.nan)
)

clean_df["Zscore"] = pd.to_numeric(
    clean_df["Zscore"],
    errors="coerce"
)

# ------------------------------------------
# 2. Clean District Rank
# ------------------------------------------

clean_df["district_rank"] = (
    clean_df["district_rank"]
    .astype(str)
    .str.extract(r"(\d+)")[0]
)

clean_df["district_rank"] = pd.to_numeric(
    clean_df["district_rank"],
    errors="coerce"
)

# ------------------------------------------
# 3. Clean Island Rank
# ------------------------------------------

clean_df["island_rank"] = (
    clean_df["island_rank"]
    .astype(str)
    .str.extract(r"(\d+)")[0]
)

clean_df["island_rank"] = pd.to_numeric(
    clean_df["island_rank"],
    errors="coerce"
)

# ------------------------------------------
# 4. Clean Birth Date
# ------------------------------------------

clean_df["birth_date"] = pd.to_datetime(
    clean_df["birth_day"].astype(str)
    + " "
    + clean_df["birth_month"].astype(str)
    + " "
    + clean_df["birth_year"].astype(str),
    errors="coerce"
)

# ------------------------------------------
# 5. Clean Gender
# ------------------------------------------

clean_df["gender"] = (
    clean_df["gender"]
    .astype("string")
    .str.strip()
    .str.lower()
)

# ------------------------------------------
# 6. Clean text columns
# ------------------------------------------

text_columns = [
    "stream",
    "sub1",
    "sub1_r",
    "sub2",
    "sub2_r",
    "sub3",
    "sub3_r",
    "cgt_r",
    "ge_r",
    "syllabus"
]

for column in text_columns:
    clean_df[column] = (
        clean_df[column]
        .astype("string")
        .str.strip()
    )

# ------------------------------------------
# Show cleaned data
# ------------------------------------------

print("Cleaned dataset:")
display(clean_df.head())

print("\nData types after cleaning:")
print(clean_df.dtypes)

print("\nDataset size:")
print(clean_df.shape)

Cleaned dataset:

,index,stream,Zscore,district_rank,island_rank,al_year,sub1,sub1_r,sub2,sub2_r,sub3,sub3_r,cgt_r,ge_r,syllabus,birth_day,birth_month,birth_year,gender,birth_date
0,0,ARTS,-0.3550,4336.0,64994.0,2020,POLITICAL SCIENCE,S,DANCING(BHARATHA),C,TAMIL,S,056,S,new,31,May,2001,female,2001-05-31
1,1,ARTS,-0.2648,4154.0,62338.0,2020,POLITICAL SCIENCE,S,CARNATIC MUSIC,C,TAMIL,C,032,C,new,13,January,2002,female,2002-01-13
2,2,COMMERCE,-0.4760,6910.0,37307.0,2020,ECONOMICS,S,BUSINESS STUDIES,S,ACCOUNTING,S,050,S,new,16,August,2001,female,2001-08-16
3,3,COMMERCE,-0.1012,5678.0,30449.0,2020,ECONOMICS,C,BUSINESS STUDIES,C,ACCOUNTING,S,034,S,new,16,August,2001,female,2001-08-16
4,4,COMMERCE,0.6014,3269.0,17010.0,2020,ECONOMICS,C,BUSINESS STUDIES,C,ACCOUNTING,B,036,S,new,7,August,2000,female,2000-08-07

Data types after cleaning:
index                     int64
stream           string[python]
Zscore                  float64
district_rank           float64
island_rank             float64
al_year                   int64
sub1             string[python]
sub1_r           string[python]
sub2             string[python]
sub2_r           string[python]
sub3             string[python]
sub3_r           string[python]
cgt_r            string[python]
ge_r             string[python]
syllabus         string[python]
birth_day                object
birth_month              object
birth_year               object
gender           string[python]
birth_date       datetime64[ns]
dtype: object

Dataset size:
(337553, 20)

In [ ]:
# ==========================================
# CELL 3 - CREATE SUBJECT DATA
# ==========================================

# Subject 1
subject1 = clean_df[[
    "index",
    "stream",
    "Zscore",
    "district_rank",
    "island_rank",
    "al_year",
    "sub1",
    "sub1_r",
    "syllabus",
    "birth_date",
    "gender"
]].copy()

subject1["subject"] = subject1["sub1"]
subject1["grade"] = subject1["sub1_r"]

# Subject 2
subject2 = clean_df[[
    "index",
    "stream",
    "Zscore",
    "district_rank",
    "island_rank",
    "al_year",
    "sub2",
    "sub2_r",
    "syllabus",
    "birth_date",
    "gender"
]].copy()

subject2["subject"] = subject2["sub2"]
subject2["grade"] = subject2["sub2_r"]

# Subject 3
subject3 = clean_df[[
    "index",
    "stream",
    "Zscore",
    "district_rank",
    "island_rank",
    "al_year",
    "sub3",
    "sub3_r",
    "syllabus",
    "birth_date",
    "gender"
]].copy()

subject3["subject"] = subject3["sub3"]
subject3["grade"] = subject3["sub3_r"]

# Keep common columns
columns = [
    "index",
    "stream",
    "Zscore",
    "district_rank",
    "island_rank",
    "al_year",
    "subject",
    "grade",
    "syllabus",
    "birth_date",
    "gender"
]

subject1 = subject1[columns]
subject2 = subject2[columns]
subject3 = subject3[columns]

# Combine all three subjects
subject_data = pd.concat(
    [subject1, subject2, subject3],
    ignore_index=True
)

print("Original student records:", len(clean_df))
print("Subject performance records:", len(subject_data))

print("\nExpected:")
print("337,553 × 3 =", 337553 * 3)

print("\nFirst 10 records:")
display(subject_data.head(10))

Original student records: 337553
Subject performance records: 1012659

Expected:
337,553 × 3 = 1012659

First 10 records:

,index,stream,Zscore,district_rank,island_rank,al_year,subject,grade,syllabus,birth_date,gender
0,0,ARTS,-0.3550,4336.0,64994.0,2020,POLITICAL SCIENCE,S,new,2001-05-31,female
1,1,ARTS,-0.2648,4154.0,62338.0,2020,POLITICAL SCIENCE,S,new,2002-01-13,female
2,2,COMMERCE,-0.4760,6910.0,37307.0,2020,ECONOMICS,S,new,2001-08-16,female
3,3,COMMERCE,-0.1012,5678.0,30449.0,2020,ECONOMICS,C,new,2001-08-16,female
4,4,COMMERCE,0.6014,3269.0,17010.0,2020,ECONOMICS,C,new,2000-08-07,female
5,5,ARTS,-0.5061,4602.0,68521.0,2020,POLITICAL SCIENCE,S,new,2002-01-09,female
6,6,ARTS,0.0177,3419.0,52426.0,2020,POLITICAL SCIENCE,S,new,2001-12-31,female
7,7,ARTS,-0.3106,4247.0,63760.0,2020,POLITICAL SCIENCE,S,new,2001-12-06,female
8,8,-,NaN,NaN,NaN,2020,ECONOMICS,S,new,2000-11-16,female
9,9,COMMERCE,1.0447,2008.0,9743.0,2020,ECONOMICS,B,new,2001-06-18,female

In [ ]:
# ==========================================
# CELL 4 - CREATE DIMENSION TABLES
# ==========================================

# ------------------------------------------
# 1. DIM STUDENT
# ------------------------------------------

dim_student = (
    subject_data[
        ["index", "gender", "birth_date"]
    ]
    .drop_duplicates(subset=["index"])
    .rename(columns={
        "index": "student_id"
    })
    .reset_index(drop=True)
)

dim_student.insert(
    0,
    "student_key",
    range(1, len(dim_student) + 1)
)

print("dim_student:", dim_student.shape)


# ------------------------------------------
# 2. DIM SUBJECT
# ------------------------------------------

dim_subject = (
    subject_data[["subject"]]
    .drop_duplicates()
    .sort_values("subject")
    .reset_index(drop=True)
)

dim_subject.insert(
    0,
    "subject_key",
    range(1, len(dim_subject) + 1)
)

dim_subject = dim_subject.rename(
    columns={"subject": "subject_name"}
)

print("dim_subject:", dim_subject.shape)


# ------------------------------------------
# 3. DIM STREAM
# ------------------------------------------

dim_stream = (
    subject_data[["stream"]]
    .drop_duplicates()
    .sort_values("stream")
    .reset_index(drop=True)
)

dim_stream.insert(
    0,
    "stream_key",
    range(1, len(dim_stream) + 1)
)

dim_stream = dim_stream.rename(
    columns={"stream": "stream_name"}
)

print("dim_stream:", dim_stream.shape)


# ------------------------------------------
# 4. DIM EXAM
# ------------------------------------------

dim_exam = (
    subject_data[["al_year"]]
    .drop_duplicates()
    .sort_values("al_year")
    .reset_index(drop=True)
)

dim_exam.insert(
    0,
    "exam_key",
    range(1, len(dim_exam) + 1)
)

dim_exam = dim_exam.rename(
    columns={"al_year": "exam_year"}
)

print("dim_exam:", dim_exam.shape)


# ------------------------------------------
# 5. DIM SYLLABUS
# ------------------------------------------

dim_syllabus = (
    subject_data[["syllabus"]]
    .drop_duplicates()
    .sort_values("syllabus")
    .reset_index(drop=True)
)

dim_syllabus.insert(
    0,
    "syllabus_key",
    range(1, len(dim_syllabus) + 1)
)

dim_syllabus = dim_syllabus.rename(
    columns={"syllabus": "syllabus_name"}
)

print("dim_syllabus:", dim_syllabus.shape)


# ==========================================
# DISPLAY DIMENSIONS
# ==========================================

print("\n========== DIM STUDENT ==========")
display(dim_student.head())

print("\n========== DIM SUBJECT ==========")
display(dim_subject)

print("\n========== DIM STREAM ==========")
display(dim_stream)

print("\n========== DIM EXAM ==========")
display(dim_exam)

print("\n========== DIM SYLLABUS ==========")
display(dim_syllabus)

dim_student: (337553, 4)
dim_subject: (62, 2)
dim_stream: (8, 2)
dim_exam: (1, 2)
dim_syllabus: (2, 2)

========== DIM STUDENT ==========

   student_key  student_id  gender birth_date
0            1           0  female 2001-05-31
1            2           1  female 2002-01-13
2            3           2  female 2001-08-16
3            4           3  female 2001-08-16
4            5           4  female 2000-08-07

========== DIM SUBJECT ==========

    subject_key            subject_name
0             1              ACCOUNTING
1             2    AGRICULTURAL SCIENCE
2             3         AGRO TECHNOLOGY
3             4                  ARABIC
4             5                     ART
..          ...                     ...
57           58                SANSKRIT
58           59  SCIENCE FOR TECHNOLOGY
59           60                 SINHALA
60           61                   TAMIL
61           62           WESTERN MUSIC

[62 rows x 2 columns]

========== DIM STREAM ==========

   stream_key             stream_name
0           1                       -
1           2                    ARTS
2           3      BIOLOGICAL SCIENCE
3           4   BIOSYSTEMS TECHNOLOGY
4           5                COMMERCE
5           6  ENGINEERING TECHNOLOGY
6           7                     NON
7           8        PHYSICAL SCIENCE

========== DIM EXAM ==========

   exam_key  exam_year
0         1       2020

========== DIM SYLLABUS ==========

   syllabus_key syllabus_name
0             1           new
1             2           old

In [ ]:
# ==========================================
# CELL 5 - CREATE FACT TABLE
# ==========================================

# Start with subject performance data
fact_student_subject = subject_data.copy()

# ------------------------------------------
# 1. Connect STUDENT dimension
# ------------------------------------------

fact_student_subject = fact_student_subject.merge(
    dim_student[["student_key", "student_id"]],
    left_on="index",
    right_on="student_id",
    how="left"
)

# ------------------------------------------
# 2. Connect SUBJECT dimension
# ------------------------------------------

fact_student_subject = fact_student_subject.merge(
    dim_subject[["subject_key", "subject_name"]],
    left_on="subject",
    right_on="subject_name",
    how="left"
)

# ------------------------------------------
# 3. Connect STREAM dimension
# ------------------------------------------

fact_student_subject = fact_student_subject.merge(
    dim_stream[["stream_key", "stream_name"]],
    left_on="stream",
    right_on="stream_name",
    how="left"
)

# ------------------------------------------
# 4. Connect EXAM dimension
# ------------------------------------------

fact_student_subject = fact_student_subject.merge(
    dim_exam[["exam_key", "exam_year"]],
    left_on="al_year",
    right_on="exam_year",
    how="left"
)

# ------------------------------------------
# 5. Connect SYLLABUS dimension
# ------------------------------------------

fact_student_subject = fact_student_subject.merge(
    dim_syllabus[["syllabus_key", "syllabus_name"]],
    left_on="syllabus",
    right_on="syllabus_name",
    how="left"
)

# ------------------------------------------
# 6. Select final fact columns
# ------------------------------------------

fact_student_subject = fact_student_subject[
    [
        "student_key",
        "subject_key",
        "stream_key",
        "exam_key",
        "syllabus_key",
        "Zscore",
        "district_rank",
        "island_rank",
        "grade"
    ]
].copy()

# ------------------------------------------
# 7. Create fact key
# ------------------------------------------

fact_student_subject.insert(
    0,
    "fact_key",
    range(1, len(fact_student_subject) + 1)
)

# ==========================================
# DISPLAY RESULTS
# ==========================================

print("Fact table shape:")
print(fact_student_subject.shape)

print("\nExpected:")
print(1012659, "rows")

print("\nFirst 10 fact records:")
display(fact_student_subject.head(10))

print("\nData types:")
print(fact_student_subject.dtypes)

print("\nMissing dimension keys:")
print(
    fact_student_subject[
        [
            "student_key",
            "subject_key",
            "stream_key",
            "exam_key",
            "syllabus_key"
        ]
    ].isnull().sum()
)

Fact table shape:
(1012659, 10)

Expected:
1012659 rows

First 10 fact records:

,fact_key,student_key,subject_key,stream_key,exam_key,syllabus_key,Zscore,district_rank,island_rank,grade
0,1,1,56,2,1,1,-0.3550,4336.0,64994.0,S
1,2,2,56,2,1,1,-0.2648,4154.0,62338.0,S
2,3,3,26,5,1,1,-0.4760,6910.0,37307.0,S
3,4,4,26,5,1,1,-0.1012,5678.0,30449.0,C
4,5,5,26,5,1,1,0.6014,3269.0,17010.0,C
5,6,6,56,2,1,1,-0.5061,4602.0,68521.0,S
6,7,7,56,2,1,1,0.0177,3419.0,52426.0,S
7,8,8,56,2,1,1,-0.3106,4247.0,63760.0,S
8,9,9,26,1,1,1,NaN,NaN,NaN,S
9,10,10,26,5,1,1,1.0447,2008.0,9743.0,B

Data types:
fact_key                  int64
student_key               int64
subject_key               int64
stream_key                int64
exam_key                  int64
syllabus_key              int64
Zscore                  float64
district_rank           float64
island_rank             float64
grade            string[python]
dtype: object

Missing dimension keys:
student_key     0
subject_key     0
stream_key      0
exam_key        0
syllabus_key    0
dtype: int64

In [ ]:
# ==========================================
# CELL 6 - EXPORT DATA WAREHOUSE TABLES
# ==========================================

# Export dimension tables
dim_student.to_csv(
    "dim_student.csv",
    index=False
)

dim_subject.to_csv(
    "dim_subject.csv",
    index=False
)

dim_stream.to_csv(
    "dim_stream.csv",
    index=False
)

dim_exam.to_csv(
    "dim_exam.csv",
    index=False
)

dim_syllabus.to_csv(
    "dim_syllabus.csv",
    index=False
)

# Export fact table
fact_student_subject.to_csv(
    "fact_student_subject.csv",
    index=False
)

print("All Data Warehouse tables exported successfully!")

print("\nFiles created:")

files = [
    "dim_student.csv",
    "dim_subject.csv",
    "dim_stream.csv",
    "dim_exam.csv",
    "dim_syllabus.csv",
    "fact_student_subject.csv"
]

for file in files:
    print("✓", file)

All Data Warehouse tables exported successfully!

Files created:
✓ dim_student.csv
✓ dim_subject.csv
✓ dim_stream.csv
✓ dim_exam.csv
✓ dim_syllabus.csv
✓ fact_student_subject.csv

In [ ]:
# Download all Data Warehouse CSV files

from google.colab import files

files_to_download = [
    "dim_student.csv",
    "dim_subject.csv",
    "dim_stream.csv",
    "dim_exam.csv",
    "dim_syllabus.csv",
    "fact_student_subject.csv"
]

for file_name in files_to_download:
    print("Downloading:", file_name)
    files.download(file_name)

Downloading: dim_student.csv

Downloading: dim_subject.csv

Downloading: dim_stream.csv

Downloading: dim_exam.csv

Downloading: dim_syllabus.csv

Downloading: fact_student_subject.csv

In [ ]:
# Fix rank columns for PostgreSQL integer import

fact_student_subject["district_rank"] = (
    pd.to_numeric(fact_student_subject["district_rank"], errors="coerce")
    .round()
    .astype("Int64")
)

fact_student_subject["island_rank"] = (
    pd.to_numeric(fact_student_subject["island_rank"], errors="coerce")
    .round()
    .astype("Int64")
)

# Make sure other integer key columns are integers
fact_student_subject["fact_key"] = fact_student_subject["fact_key"].astype("int64")
fact_student_subject["student_key"] = fact_student_subject["student_key"].astype("int64")
fact_student_subject["subject_key"] = fact_student_subject["subject_key"].astype("int64")
fact_student_subject["stream_key"] = fact_student_subject["stream_key"].astype("int64")
fact_student_subject["exam_key"] = fact_student_subject["exam_key"].astype("int64")
fact_student_subject["syllabus_key"] = fact_student_subject["syllabus_key"].astype("int64")

# Check the result
print(fact_student_subject[
    ["district_rank", "island_rank"]
].head())

print("\nData types:")
print(fact_student_subject.dtypes)

   district_rank  island_rank
0           4336        64994
1           4154        62338
2           6910        37307
3           5678        30449
4           3269        17010

Data types:
fact_key                  int64
student_key               int64
subject_key               int64
stream_key                int64
exam_key                  int64
syllabus_key              int64
Zscore                  float64
district_rank             Int64
island_rank               Int64
grade            string[python]
dtype: object

In [ ]:
fact_student_subject.to_csv(
    "fact_student_subject.csv",
    index=False
)

print("Corrected fact CSV created successfully.")

Corrected fact CSV created successfully.

In [ ]:
from google.colab import files

files.download("fact_student_subject.csv")

In [ ]:
# ============================================================
# GCE A/L STUDENT PERFORMANCE DATA WAREHOUSE REPORT
# PDF GENERATOR - GOOGLE COLAB
# ============================================================

# Install required libraries
!pip -q install reportlab

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, KeepTogether
)
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics
from google.colab import files
import os

# ============================================================
# 1. PDF SETTINGS
# ============================================================

output_file = "/content/AL_Student_Data_Warehouse_Report.pdf"

doc = SimpleDocTemplate(
    output_file,
    pagesize=A4,
    rightMargin=1.8*cm,
    leftMargin=1.8*cm,
    topMargin=2*cm,
    bottomMargin=2*cm
)

# ============================================================
# 2. STYLES
# ============================================================

styles = getSampleStyleSheet()

title_style = ParagraphStyle(
    "ReportTitle",
    parent=styles["Title"],
    fontSize=24,
    leading=30,
    alignment=TA_CENTER,
    spaceAfter=20
)

subtitle_style = ParagraphStyle(
    "Subtitle",
    parent=styles["Normal"],
    fontSize=13,
    leading=18,
    alignment=TA_CENTER,
    spaceAfter=10
)

h1 = ParagraphStyle(
    "Heading1Custom",
    parent=styles["Heading1"],
    fontSize=17,
    leading=22,
    spaceBefore=14,
    spaceAfter=10
)

h2 = ParagraphStyle(
    "Heading2Custom",
    parent=styles["Heading2"],
    fontSize=13,
    leading=18,
    spaceBefore=10,
    spaceAfter=7
)

body = ParagraphStyle(
    "BodyCustom",
    parent=styles["BodyText"],
    fontSize=10.5,
    leading=16,
    spaceAfter=8
)

small = ParagraphStyle(
    "Small",
    parent=styles["BodyText"],
    fontSize=9,
    leading=13
)

toc_style = ParagraphStyle(
    "TOC",
    parent=styles["BodyText"],
    fontSize=11,
    leading=20
)

code_style = ParagraphStyle(
    "Code",
    parent=styles["Code"],
    fontName="Courier",
    fontSize=7.5,
    leading=10,
    leftIndent=8,
    rightIndent=8,
    spaceBefore=5,
    spaceAfter=8
)

center = ParagraphStyle(
    "Center",
    parent=styles["BodyText"],
    fontSize=10,
    alignment=TA_CENTER,
    leading=15
)

# ============================================================
# 3. HEADER / FOOTER
# ============================================================

def add_page_number(canvas, doc):
    canvas.saveState()

    canvas.setFont("Helvetica", 8)
    canvas.drawCentredString(
        A4[0] / 2,
        0.9*cm,
        f"AL Student Performance Data Warehouse | Page {doc.page}"
    )

    canvas.restoreState()

# ============================================================
# 4. HELPER FUNCTIONS
# ============================================================

story = []

def P(text, style=body):
    story.append(Paragraph(text, style))

def H1(text):
    story.append(Paragraph(text, h1))

def H2(text):
    story.append(Paragraph(text, h2))

def SP(height=8):
    story.append(Spacer(1, height))

def make_table(data, widths=None, header=True):
    formatted = []

    for r, row in enumerate(data):
        new_row = []

        for cell in row:
            if isinstance(cell, Paragraph):
                new_row.append(cell)
            else:
                new_row.append(
                    Paragraph(
                        str(cell),
                        small
                    )
                )

        formatted.append(new_row)

    t = Table(formatted, colWidths=widths, repeatRows=1 if header else 0)

    commands = [
        ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
        ("VALIGN", (0,0), (-1,-1), "TOP"),
        ("LEFTPADDING", (0,0), (-1,-1), 6),
        ("RIGHTPADDING", (0,0), (-1,-1), 6),
        ("TOPPADDING", (0,0), (-1,-1), 5),
        ("BOTTOMPADDING", (0,0), (-1,-1), 5),
    ]

    if header:
        commands.extend([
            ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ])

    t.setStyle(TableStyle(commands))

    story.append(t)
    SP(10)

# ============================================================
# 5. TITLE PAGE
# ============================================================

SP(50)

P(
    "GCE ADVANCED LEVEL STUDENT PERFORMANCE",
    title_style
)

P(
    "DATA WAREHOUSE PROJECT REPORT",
    title_style
)

SP(20)

P(
    "Student Performance (GCE AL Exam 2020 - Sri Lanka)",
    subtitle_style
)

SP(25)

P(
    "<b>Data Source:</b> Kaggle",
    center
)

P(
    "<b>ETL Platform:</b> Google Colab, Python and Pandas",
    center
)

P(
    "<b>Data Warehouse:</b> PostgreSQL 18",
    center
)

P(
    "<b>Database Management Tool:</b> pgAdmin",
    center
)

SP(35)

P(
    "<b>Project Summary</b>",
    h2
)

P(
    "This project develops a dimensional Data Warehouse for analysing "
    "Sri Lankan GCE Advanced Level examination performance data from 2020. "
    "The raw Kaggle dataset was extracted, cleaned and transformed using "
    "Python and Pandas in Google Colab and subsequently loaded into a "
    "PostgreSQL Data Warehouse using a Star Schema.",
    body
)

SP(20)

P(
    "Prepared for Academic Data Warehousing Study",
    center
)

story.append(PageBreak())

# ============================================================
# 6. TABLE OF CONTENTS
# ============================================================

H1("Table of Contents")

toc_items = [
    "1. Introduction",
    "2. Dataset Description",
    "3. Data Warehouse Analytical Requirements",
    "4. ETL Process",
    "5. Data Cleaning and Transformation",
    "6. Data Warehouse Architecture",
    "7. Star Schema Design",
    "8. Fact Table",
    "9. Dimension Tables",
    "10. PostgreSQL Implementation",
    "11. Data Loading and Validation",
    "12. Analytical SQL Queries",
    "13. Example Analytical Results",
    "14. Why Star Schema Was Selected",
    "15. Data Warehouse Advantages",
    "16. Limitations",
    "17. Conclusion",
    "18. References"
]

for item in toc_items:
    P(item, toc_style)

story.append(PageBreak())

# ============================================================
# 7. INTRODUCTION
# ============================================================

H1("1. Introduction")

P(
    "A Data Warehouse is a centralized repository designed primarily for "
    "analysis, reporting and decision making. Unlike an operational database "
    "that focuses on day-to-day transactions, a Data Warehouse organizes "
    "historical data so that users can analyse information from multiple "
    "perspectives."
)

P(
    "This project develops a Data Warehouse using the Sri Lankan GCE "
    "Advanced Level examination dataset for the year 2020. The objective is "
    "to transform the original flat CSV dataset into a dimensional model "
    "that supports analytical queries related to student performance."
)

P(
    "The implemented solution uses Google Colab with Python and Pandas for "
    "the Extract and Transform stages and PostgreSQL 18 with pgAdmin for "
    "the Load stage."
)

# ============================================================
# 8. DATASET DESCRIPTION
# ============================================================

H1("2. Dataset Description")

P(
    "The source dataset is the Kaggle dataset titled "
    "<b>Student Performance (GCE AL Exam_2020 - Sri Lanka)</b>. "
    "The dataset contains examination-related information for students who "
    "participated in the 2020 Sri Lankan GCE Advanced Level examination."
)

dataset_data = [
    ["Property", "Value"],
    ["Source", "Kaggle"],
    ["Examination Year", "2020"],
    ["Original Records", "337,553"],
    ["Original Columns", "19"],
    ["Subject Records after transformation", "1,012,659"],
]

make_table(dataset_data, [6*cm, 9*cm])

H2("Main Source Attributes")

source_columns = [
    ["Column", "Description"],
    ["index", "Original student record identifier"],
    ["stream", "A/L study stream"],
    ["Zscore", "Student Z-score"],
    ["district_rank", "District examination rank"],
    ["island_rank", "Island-wide examination rank"],
    ["al_year", "Examination year"],
    ["sub1 / sub1_r", "First subject and grade"],
    ["sub2 / sub2_r", "Second subject and grade"],
    ["sub3 / sub3_r", "Third subject and grade"],
    ["cgt_r", "Common General Test result"],
    ["ge_r", "General English result"],
    ["syllabus", "New or old syllabus"],
    ["birth_day/month/year", "Student birth date components"],
    ["gender", "Student gender"],
]

make_table(source_columns, [5*cm, 10*cm])

# ============================================================
# 9. ANALYTICAL REQUIREMENTS
# ============================================================

H1("3. Data Warehouse Analytical Requirements")

P(
    "The Data Warehouse was designed around the analytical questions that "
    "can be answered using the student performance data. The main analytical "
    "requirements are:"
)

requirements = [
    "Analyse examination performance by subject.",
    "Compare performance between different A/L streams.",
    "Analyse student performance by gender.",
    "Compare performance between new and old syllabi.",
    "Analyse grade distributions for individual subjects.",
    "Analyse Z-score performance.",
    "Analyse district and island rankings.",
    "Support multidimensional reporting and decision making."
]

for i, req in enumerate(requirements, 1):
    P(f"<b>{i}.</b> {req}")

# ============================================================
# 10. ETL PROCESS
# ============================================================

H1("4. ETL Process")

H2("4.1 Extract")

P(
    "The original student performance CSV file was obtained from Kaggle. "
    "The dataset was loaded into Google Colab using Python and Pandas. "
    "The initial dataset contained 337,553 records and 19 columns."
)

H2("4.2 Transform")

P(
    "The transformation stage prepared the raw data for dimensional "
    "modelling. Z-score values and ranking fields were converted into "
    "numeric values. The separate birth day, month and year fields were "
    "combined into a single birth_date field."
)

P(
    "The three subject columns were also reshaped. The original structure "
    "stored three subjects horizontally in each student record. These were "
    "converted into separate subject-performance rows. As a result, each "
    "student can have three records in the fact table."
)

H2("4.3 Load")

P(
    "After transformation, the dimension and fact tables were exported "
    "as CSV files from Google Colab. These CSV files were then imported "
    "into PostgreSQL using pgAdmin."
)

P(
    "<b>ETL Flow:</b> Kaggle CSV → Python/Pandas → Cleaned Data → "
    "Dimensional Model → CSV Files → PostgreSQL Data Warehouse"
)

# ============================================================
# 11. DATA CLEANING
# ============================================================

H1("5. Data Cleaning and Transformation")

cleaning_data = [
    ["Transformation", "Purpose"],
    ["Convert Z-score to numeric", "Enable numerical analysis"],
    ["Convert district rank to integer", "Match PostgreSQL data type"],
    ["Convert island rank to integer", "Match PostgreSQL data type"],
    ["Combine birth date fields", "Create a proper DATE value"],
    ["Clean text fields", "Remove unwanted spaces and normalize values"],
    ["Reshape subject columns", "Create one student-subject fact record"],
    ["Handle missing values", "Preserve source information without inventing values"],
]

make_table(cleaning_data, [6*cm, 9*cm])

P(
    "During the PostgreSQL loading stage, two data-type issues were "
    "identified and corrected. Rank values such as 4336.0 were converted "
    "to integers because the database columns were defined as INTEGER. "
    "The grade value 'Absent' was also identified; the grade column was "
    "therefore expanded from VARCHAR(5) to VARCHAR(10)."
)

# ============================================================
# 12. ARCHITECTURE
# ============================================================

H1("6. Data Warehouse Architecture")

P(
    "The implemented Data Warehouse follows a dimensional architecture. "
    "The central fact table contains student-subject performance, while "
    "five dimension tables provide descriptive context for analysis."
)

architecture = [
    ["Component", "Technology / Purpose"],
    ["Source", "Kaggle CSV dataset"],
    ["Extract & Transform", "Google Colab + Python + Pandas"],
    ["Data Warehouse", "PostgreSQL 18"],
    ["Database Interface", "pgAdmin"],
    ["Schema Type", "Star Schema"],
    ["Fact Table", "fact_student_subject"],
    ["Dimension Tables", "5 dimensions"],
]

make_table(architecture, [6*cm, 9*cm])

# ============================================================
# 13. STAR SCHEMA
# ============================================================

H1("7. Star Schema Design")

P(
    "A Star Schema is a Data Warehouse modelling technique in which a "
    "central fact table is directly connected to several dimension tables. "
    "The model resembles a star because the fact table is located at the "
    "centre and the dimensions surround it."
)

P(
    "<b>Implemented Star Schema:</b>"
)

star_schema = [
    ["Dimension Table", "Relationship", "Central Fact Table"],
    ["dim_student", "student_key", "fact_student_subject"],
    ["dim_subject", "subject_key", "fact_student_subject"],
    ["dim_stream", "stream_key", "fact_student_subject"],
    ["dim_exam", "exam_key", "fact_student_subject"],
    ["dim_syllabus", "syllabus_key", "fact_student_subject"],
]

make_table(star_schema, [5*cm, 4*cm, 6*cm])

P(
    "<b>Simple representation:</b><br/><br/>"
    "dim_student &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "
    "dim_subject<br/>"
    "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "
    "↓<br/>"
    "dim_stream → <b>fact_student_subject</b> ← dim_exam<br/>"
    "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "
    "↑<br/>"
    "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "
    "dim_syllabus"
)

# ============================================================
# 14. FACT TABLE
# ============================================================

H1("8. Fact Table")

H2("fact_student_subject")

P(
    "The fact table is the central table in the Data Warehouse. Its grain "
    "is <b>one row per student per subject performance</b>. Since the source "
    "dataset contains three subjects for each student, the resulting fact "
    "table contains 1,012,659 records."
)

fact_data = [
    ["Column", "Purpose"],
    ["fact_key", "Unique fact record identifier"],
    ["student_key", "Links to dim_student"],
    ["subject_key", "Links to dim_subject"],
    ["stream_key", "Links to dim_stream"],
    ["exam_key", "Links to dim_exam"],
    ["syllabus_key", "Links to dim_syllabus"],
    ["z_score", "Student Z-score"],
    ["district_rank", "District rank"],
    ["island_rank", "Island-wide rank"],
    ["grade", "Subject grade/result"],
]

make_table(fact_data, [5*cm, 10*cm])

P(
    "<b>Fact table size:</b> 1,012,659 records"
)

# ============================================================
# 15. DIMENSIONS
# ============================================================

H1("9. Dimension Tables")

dimension_data = [
    ["Dimension", "Rows", "Purpose"],
    ["dim_student", "337,553", "Student descriptive information"],
    ["dim_subject", "62", "Subject information"],
    ["dim_stream", "8", "A/L stream information"],
    ["dim_exam", "1", "Examination year"],
    ["dim_syllabus", "2", "New / old syllabus"],
]

make_table(dimension_data, [5*cm, 3*cm, 7*cm])

H2("dim_student")

P(
    "Stores the student dimension using a surrogate student_key together "
    "with the original student identifier, gender and birth date."
)

H2("dim_subject")

P(
    "Stores unique subject names and assigns a subject_key to each subject."
)

H2("dim_stream")

P(
    "Stores the different A/L streams found in the dataset, including "
    "Arts, Commerce, Physical Science and other source categories."
)

H2("dim_exam")

P(
    "Stores the examination year. In this dataset there is one examination "
    "year, 2020."
)

H2("dim_syllabus")

P(
    "Stores the syllabus type, which consists of new and old syllabus "
    "categories."
)

# ============================================================
# 16. POSTGRESQL
# ============================================================

H1("10. PostgreSQL Implementation")

P(
    "PostgreSQL 18 was selected as the Data Warehouse database management "
    "system. pgAdmin was used as the graphical interface for creating tables, "
    "executing SQL queries and importing the transformed CSV files."
)

H2("Main Tables Created")

P(
    "The database contains six tables: five dimension tables and one central "
    "fact table."
)

P(
    "Primary keys were created for all dimension tables and the fact table. "
    "Foreign key constraints were created in the fact table to maintain "
    "referential integrity between the fact and dimension tables."
)

# ============================================================
# 17. LOADING AND VALIDATION
# ============================================================

H1("11. Data Loading and Validation")

P(
    "The transformed CSV files were loaded into PostgreSQL in the following "
    "order: dimension tables first and the fact table afterward. Loading "
    "the dimensions first ensures that the foreign key references required "
    "by the fact table already exist."
)

validation_data = [
    ["Table", "Expected / Loaded Rows", "Status"],
    ["dim_student", "337,553", "Successful"],
    ["dim_subject", "62", "Successful"],
    ["dim_stream", "8", "Successful"],
    ["dim_exam", "1", "Successful"],
    ["dim_syllabus", "2", "Successful"],
    ["fact_student_subject", "1,012,659", "Successful"],
]

make_table(validation_data, [6*cm, 5*cm, 4*cm])

P(
    "The final row-count validation confirmed that all six tables were "
    "loaded successfully and that the fact table contains 1,012,659 records."
)

# ============================================================
# 18. ANALYTICAL SQL
# ============================================================

H1("12. Analytical SQL Queries")

H2("12.1 Average Z-score by Stream")

P(
    "This query demonstrates how the fact table can be combined with the "
    "stream dimension to calculate average student performance by stream."
)

P(
    "SELECT s.stream_name,<br/>"
    "       AVG(f.z_score) AS average_z_score<br/>"
    "FROM fact_student_subject f<br/>"
    "JOIN dim_stream s ON f.stream_key = s.stream_key<br/>"
    "GROUP BY s.stream_name<br/>"
    "ORDER BY average_z_score DESC;",
    code_style
)

H2("12.2 Average Z-score by Subject")

P(
    "SELECT s.subject_name,<br/>"
    "       AVG(f.z_score) AS average_z_score<br/>"
    "FROM fact_student_subject f<br/>"
    "JOIN dim_subject s ON f.subject_key = s.subject_key<br/>"
    "GROUP BY s.subject_name<br/>"
    "ORDER BY average_z_score DESC;",
    code_style
)

H2("12.3 Grade Distribution")

P(
    "SELECT s.subject_name,<br/>"
    "       f.grade,<br/>"
    "       COUNT(*) AS student_count<br/>"
    "FROM fact_student_subject f<br/>"
    "JOIN dim_subject s ON f.subject_key = s.subject_key<br/>"
    "GROUP BY s.subject_name, f.grade<br/>"
    "ORDER BY s.subject_name, student_count DESC;",
    code_style
)

H2("12.4 Performance by Gender")

P(
    "SELECT st.gender,<br/>"
    "       AVG(f.z_score) AS average_z_score<br/>"
    "FROM fact_student_subject f<br/>"
    "JOIN dim_student st ON f.student_key = st.student_key<br/>"
    "GROUP BY st.gender;",
    code_style
)

H2("12.5 New vs Old Syllabus")

P(
    "SELECT sy.syllabus_name,<br/>"
    "       AVG(f.z_score) AS average_z_score<br/>"
    "FROM fact_student_subject f<br/>"
    "JOIN dim_syllabus sy ON f.syllabus_key = sy.syllabus_key<br/>"
    "GROUP BY sy.syllabus_name;",
    code_style
)

# ============================================================
# 19. EXAMPLE ANALYTICAL RESULTS
# ============================================================

H1("13. Example Analytical Results")

P(
    "The Data Warehouse enables a range of analytical reports. The "
    "following are examples of the types of findings that can be produced "
    "from the warehouse."
)

results = [
    ["Analysis", "Purpose"],
    ["Average Z-score by stream", "Compare overall performance between streams"],
    ["Average Z-score by subject", "Identify relative subject performance"],
    ["Grade distribution", "Understand grades achieved in each subject"],
    ["Gender analysis", "Compare performance between genders"],
    ["Syllabus comparison", "Compare new and old syllabus performance"],
    ["Ranking analysis", "Study district and island rankings"],
]

make_table(results, [6*cm, 9*cm])

P(
    "These analytical queries demonstrate the main purpose of the Data "
    "Warehouse: converting raw examination data into structured information "
    "that can support analysis and reporting."
)

# ============================================================
# 20. WHY STAR SCHEMA
# ============================================================

H1("14. Why Star Schema Was Selected")

P(
    "The Star Schema was selected because it matches the analytical "
    "requirements of this project. The main requirement is to analyse "
    "student performance from multiple perspectives, including subject, "
    "stream, gender, examination year and syllabus."
)

P(
    "The fact table contains the performance information, while the "
    "dimension tables provide the different perspectives required for "
    "analysis."
)

P(
    "A Snowflake Schema could also be used, but it would further normalize "
    "dimension data and introduce additional tables and joins. The dimensions "
    "in this project are relatively simple, so that additional complexity "
    "is not necessary."
)

P(
    "<b>Therefore, Star Schema was chosen because it provides:</b>"
)

star_reasons = [
    "Simple and easy-to-understand structure.",
    "Fewer joins for analytical queries.",
    "Good suitability for reporting and OLAP-style analysis.",
    "Easy navigation between facts and dimensions.",
    "A clear separation between measurable facts and descriptive dimensions.",
    "A structure that directly matches the project's analytical requirements."
]

for i, reason in enumerate(star_reasons, 1):
    P(f"<b>{i}.</b> {reason}")

# ============================================================
# 21. ADVANTAGES
# ============================================================

H1("15. Data Warehouse Advantages")

advantages = [
    "Centralizes examination data into a structured analytical repository.",
    "Makes analytical queries easier than working directly with the original CSV.",
    "Separates facts from descriptive dimensions.",
    "Supports multidimensional analysis.",
    "Allows aggregation of Z-scores and ranking information.",
    "Provides a foundation for dashboards and business intelligence tools.",
    "Improves data organization for reporting and decision making."
]

for i, advantage in enumerate(advantages, 1):
    P(f"<b>{i}.</b> {advantage}")

# ============================================================
# 22. LIMITATIONS
# ============================================================

H1("16. Limitations")

P(
    "There are several limitations in the current implementation."
)

limitations = [
    "The dataset represents a single examination year, 2020.",
    "The source dataset does not provide detailed historical changes.",
    "The source does not provide a full district dimension with district names.",
    "Missing values exist in some source attributes such as gender and performance fields.",
    "The current warehouse focuses on examination performance rather than wider student information."
]

for i, limitation in enumerate(limitations, 1):
    P(f"<b>{i}.</b> {limitation}")

# ============================================================
# 23. CONCLUSION
# ============================================================

H1("17. Conclusion")

P(
    "This project successfully transformed the Sri Lankan GCE Advanced Level "
    "2020 student performance dataset into a functional Data Warehouse."
)

P(
    "The Extract, Transform and Load process was implemented using Kaggle, "
    "Python, Pandas, Google Colab and PostgreSQL. The original 337,553 "
    "student records were transformed into a dimensional structure containing "
    "five dimensions and one fact table."
)

P(
    "The final Data Warehouse contains 337,553 student dimension records, "
    "62 subjects, 8 streams, 1 examination year, 2 syllabus types and "
    "1,012,659 student-subject fact records."
)

P(
    "The Star Schema provides a simple and effective structure for analysing "
    "student performance by subject, stream, gender, syllabus and other "
    "dimensions. The implemented analytical queries demonstrate how the "
    "warehouse can support reporting and decision-making."
)

P(
    "Overall, the project demonstrates the complete Data Warehouse workflow "
    "from raw source data through ETL transformation and database loading "
    "to analytical querying."
)

# ============================================================
# 24. REFERENCES
# ============================================================

H1("18. References")

P(
    "Kaggle. Student Performance (GCE AL Exam_2020 - Sri Lanka). "
    "Dataset by Sasika Amarasinghe."
)

P(
    "PostgreSQL Documentation. PostgreSQL relational database management "
    "system documentation."
)

P(
    "Pandas Documentation. Python data analysis and manipulation library."
)

P(
    "ReportLab Documentation. Python library used to generate this PDF report."
)

# ============================================================
# 25. BUILD PDF
# ============================================================

doc.build(
    story,
    onFirstPage=add_page_number,
    onLaterPages=add_page_number
)

print("=" * 60)
print("PDF REPORT GENERATED SUCCESSFULLY")
print("=" * 60)
print(f"File: {output_file}")
print("The report includes:")
print("- Title page")
print("- Table of Contents")
print("- Dataset description")
print("- Analytical requirements")
print("- ETL process")
print("- Data cleaning")
print("- Data Warehouse architecture")
print("- Star Schema")
print("- Fact table")
print("- Dimension tables")
print("- PostgreSQL implementation")
print("- Data loading and validation")
print("- Analytical SQL queries")
print("- Star Schema justification")
print("- Advantages and limitations")
print("- Conclusion")
print("- References")
print("=" * 60)

# ============================================================
# 26. DOWNLOAD PDF
# ============================================================

files.download(output_file)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 16.9 MB/s eta 0:00:00
============================================================
PDF REPORT GENERATED SUCCESSFULLY
============================================================
File: /content/AL_Student_Data_Warehouse_Report.pdf
The report includes:
- Title page
- Table of Contents
- Dataset description
- Analytical requirements
- ETL process
- Data cleaning
- Data Warehouse architecture
- Star Schema
- Fact table
- Dimension tables
- PostgreSQL implementation
- Data loading and validation
- Analytical SQL queries
- Star Schema justification
- Advantages and limitations
- Conclusion
- References
============================================================